language: node_js
node_js:
- '8'
install:
- npm i -g metricly-cli
script:
- metricly package validate
notifications:
  slack:
    secure: oyRmAvvNsaC7mUnyi754n16qTmo3A6RTzLvaqJfZK7ONg81A14pZ5DOBN/BsTvyaWoPET/SokQBBGwF8WJxykMQ25hCM2L/cg9UlRc2ZP/PScyLAoRqjaDmHWzHRWEvkQoh1qJ6HJydX3nZUX4sL18p8iGN2xvcYVpawCHdOBrwxxoMEw8xycX7PpLep7UwnCaSMQ5H/DsWOWZB55iq55IXRrAlMe239aHY3KJjP0LSdnnMiyrVM43Yhuw0P4ddjJ67Np8yhE2VJiiqgRREuuSCX5FY1YcxHpqGQ1gzBCU4YyXqHiqcRzH1ZwVQ+7OIQxMN4K7s/ktEGWDpEt2iAHIQJsUR4TsgFslJ2WdssLu0mNVwBOXfWQgKG/qaw0MrijgOhjx4j2Nc4aDuRAoiOalYwS3SElJz8KGTJNdalUUIc6SfhvWMQ1kM2aLmRw6MZRf19tKwZ4CPdRBjfgDbUoUDbmDmFoxDNMxLZmCbC3vy/7uPzig9WBMGqXRBvQmRYxe68/RUPBX+uX6m5YxjvWfGOEQ5DHfpshB8ZNpo+sLhzjOG0zvDO4eUmQ43WSl9F/WeFJvym46ZqWbc0LkS2z5k3aME5lF1nX7ouYQQARtXAOMQk8I2a+dfDx5jmRGWPaW8GQ5aY7qnSO819teNnXJWlbb9t86YlU4a6EDcoLMY=
